on:
  push:
    branches:
      - main
      - renovate/**
    paths-ignore:
      - xtask
      - README.md
      - update.sh
      - .github/workflows/update.yml

  pull_request:
    branches:
      - main
    paths-ignore:
      - xtask
      - README.md
      - update.sh
      - .github/workflows/update.yml

  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

name: Build nix packages
jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # tag=v2

    - name: Install Nix
      uses: cachix/install-nix-action@d56f3ce9be45c562799280e8a561fbbe8f36de44 # tag=v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install and enable cachix
      run: |
        nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
        cachix use msfjarvis
        cachix authtoken ${CACHIX_AUTH_TOKEN}
      env:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build Nix packages
      run: |
        # Compile all packages
        nix-build
        # Compile again, but since it's already cached we simply get a list of store paths
        # that can be pushed to cachix.
        nix-build | cachix push msfjarvis --omit-deriver -c9
env:
  NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1
