on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to check updates for'
        required: false
      version:
        description: 'Version to pin package to'
        required: false

name: Check for package updates
jobs:
  check-nix-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # tag=v2

    - name: Install Nix
      uses: cachix/install-nix-action@d56f3ce9be45c562799280e8a561fbbe8f36de44 # tag=v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Set Git user and email
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com

    - name: Check pre-update Git ref
      run: |
        echo "OLD_REF=$(git rev-parse HEAD)" >> "$GITHUB_ENV"

    - name: Install and enable cachix
      run: |
        nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
        cachix use msfjarvis

    - name: Enable cachix binary cache
      run: cachix use msfjarvis

    - name: Check for updates of given package
      if: "github.event.inputs.package != null"
      run: nix-shell -p nix-update git --run './update.sh ${{ github.event.inputs.package }} ${{ github.event.inputs.version }}'

    - name: Check for updates
      if: "github.event.inputs.package == null"
      run: nix-shell -p nix-update git --run ./update.sh

    - name: Check post-update Git ref
      run: |
        echo "NEW_REF=$(git rev-parse HEAD)" >> "$GITHUB_ENV"

    - name: Push to main branch
      if: env.OLD_REF != env.NEW_REF
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.WORKFLOW_KICKOFF_TOKEN }}
      run: |
        git push origin main
        gh workflow run build.yml
