on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to check updates for'
        required: false
      version:
        description: 'Version to pin package to'
        required: false

name: Check for package updates
jobs:
  check-nix-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@bc7b19257469c8029b46f45ac99ecc11156c8b2d # v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        extra-conf: |
          trusted-substituters = https://cache.nixos.org https://nix-community.cachix.org https://cache.garnix.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=    

    - name: Set Git user and email
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com

    - name: Check pre-update Git ref
      run: |
        echo "OLD_REF=$(git rev-parse HEAD)" >> "$GITHUB_ENV"

    - name: Check for updates of given package
      if: "github.event.inputs.package != null"
      run: nix-shell -p nix-update git --run './update.sh ${{ github.event.inputs.package }} ${{ github.event.inputs.version }}'

    - name: Check for updates
      if: "github.event.inputs.package == null"
      run: nix-shell -p nix-update git --run ./update.sh

    - name: Check post-update Git ref
      run: |
        echo "NEW_REF=$(git rev-parse HEAD)" >> "$GITHUB_ENV"

    - name: Push to main branch
      if: env.OLD_REF != env.NEW_REF
      shell: bash
      run: |
        git push origin main
